site_name: Web3-wiki

nav:
- 首页: "index.md"
- "基本的区块链知识":
  - "什么是区块链":
    - "基本的区块链知识/什么是区块链/index.md"
    - "相关网页中文翻译":
      - "区块链定义解释": "基本的区块链知识/中文网页/什么是区块链-中文网页/区块链定义解释.md"
      - "什么是去中心化？": "基本的区块链知识/中文网页/什么是区块链-中文网页/什么是去中心化？.md"
  - "权力下放": 
    - "基本的区块链知识/权力下放/index.md"
    - "相关网页中文翻译":
      - "什么是权力下放？": "基本的区块链知识/中文网页/权力下放-中文网页/什么是权力下放？.md"
      - "在区块链中，权力下放的作用是什么？": "基本的区块链知识/中文网页/权力下放-中文网页/在区块链中，权力下放的作用是什么？.md"
  - "为什么区块链重要":
    - "基本的区块链知识/为什么区块链重要/index.md"
    - "相关网页中文翻译":
      - "为什么是区块链？": "基本的区块链知识/中文网页/为什么区块链重要-中文网页/为什么是区块链？.md"
      - "什么是区块链，为什么它很重要？": "基本的区块链知识/中文网页/为什么区块链重要-中文网页/什么是区块链，为什么它很重要？.md"
      - "Web3/密码:为什么要兼得？": "基本的区块链知识/中文网页/为什么区块链重要-中文网页/Web3&密码为什么要兼得？.md"
      - "为什么区块链很重要以及为什么它很重要": "基本的区块链知识/中文网页/为什么区块链重要-中文网页/为什么区块链很重要以及为什么它很重要.md"
  - "区块链结构":
    - "基本的区块链知识/区块链结构/index.md"
    - "相关网页中文翻译":
      - "区块链架构基础：组件、结构、收益和创造": "基本的区块链知识/中文网页/区块链结构-中文网页/区块链架构基础：组件、结构、收益和创造.md"
      - "区块链架构 101：组件、结构和优势": "基本的区块链知识/中文网页/区块链结构-中文网页/区块链架构 101：组件、结构和优势.md"
      - "区块链结构": "基本的区块链知识/中文网页/区块链结构-中文网页/区块链结构.md"
  - "基本区块链操作":
    - "基本的区块链知识/基本区块链操作/index.md"
    - "相关网页中文翻译":
      - "区块链基础知识：结构、操作和比特币区块链": "基本的区块链知识/中文网页/基本区块链操作-中文网页/区块链基础知识：结构、操作和比特币区块链.md"
      - "比特币区块链交易 | 比特币开发者": "基本的区块链知识/中文网页/基本区块链操作-中文网页/比特币区块链交易--比特币开发者.md"
  - "区块链技术的应用和用途":
    - "基本的区块链知识/区块链技术的应用和用途/index.md"
    - "相关网页中文翻译":
      - "区块链技术的十大现实应用": "基本的区块链知识/中文网页/区块链技术的应用和用途-中文网页/区块链技术的十大现实应用.md"
      - "打破现状的区块链应用和现实世界用例 E34": "基本的区块链知识/中文网页/区块链技术的应用和用途-中文网页/打破现状的区块链应用和现实世界用例 E34.md"
- "区块链常识":
  - "贮存":
    - "正文": "区块链常识/贮存.md"
    - "相关网页中文翻译":
      - "区块链贮存": "区块链常识/中文网页/贮存-中文网页/区块链贮存.md"
      - "IPFS的工作原理": "区块链常识/中文网页/贮存-中文网页/IPFS的工作原理.md"
  - "挖矿和激励模型":
    - "正文": "区块链常识/挖矿和激励模型.md"
    - "相关网页中文翻译":
      - "区块链对矿工的激励": "区块链常识/中文网页/挖矿和激励模型-中文网页/区块链对矿工的激励.md"
      - "Solana 质押奖励": "区块链常识/中文网页/挖矿和激励模型-中文网页/Solana 质押奖励.md"
  - "权力下放与信任":
    - "正文": "区块链常识/权力下放与信任.md"
    - "相关网页中文翻译":
      - "加密货币到底是什么": "区块链常识/中文网页/权力下放与信任-中文网页/加密货币到底是什么.md"
  - "区块链分叉":
    - "正文": "区块链常识/区块链分叉.md"
    - "相关网页中文翻译":
      - "什么是分叉？": "区块链常识/中文网页/区块链分叉-中文网页/什么是分叉？.md"
      - "什么是硬分叉？": "区块链常识/中文网页/区块链分叉-中文网页/什么是硬分叉？.md"
  - "加密货币":
    - "正文": "区块链常识/加密货币.md"
    - "相关网页中文翻译":
      - "什么是加密货币？": "区块链常识/中文网页/加密货币-中文网页/什么是加密货币？.md"
      - "加密货币是什么以及是怎样运作的？": "区块链常识/中文网页/加密货币-中文网页/加密货币是什么以及是怎样运作的？.md"
  - "加密钱包":
    - "正文": "区块链常识/加密钱包.md"
    - "相关网页中文翻译":
      - "什么是区块链钱包？": "区块链常识/中文网页/加密钱包-中文网页/什么是区块链钱包？.md"
      - "什么是加密钱包？ 初学者指南": "区块链常识/中文网页/加密钱包-中文网页/什么是加密钱包？ 初学者指南.md"
  - "密码学":
    - "正文": "区块链常识/密码学.md"
    - "相关网页中文翻译":
      - "什么是密码学？": "区块链常识/中文网页/密码学-中文网页/什么是密码学？.md"
  - "共识协议":
    - "正文": "区块链常识/共识协议.md"
    - "相关网页中文翻译":
      - "区块链中的共识机制：初学者指南": "区块链常识/中文网页/共识协议-中文网页/区块链中的共识机制：初学者指南.md"
      - "什么是共识机制？": "区块链常识/中文网页/共识协议-中文网页/什么是共识机制？.md"
  - "区块链互操作性":
    - "正文": "区块链常识/区块链互操作性.md"
    - "相关网页中文翻译":
      - "跨链互操作性：对区块链意味着什么": "区块链常识/中文网页/区块链互操作性-中文网页/跨链互操作性：对区块链意味着什么.md"
      - "区块链互操作性：为什么跨链技术很重要？": "区块链常识/中文网页/区块链互操作性-中文网页/区块链互操作性：为什么跨链技术很重要？.md"
      - "区块链互操作性——了解跨链技术": "区块链常识/中文网页/区块链互操作性-中文网页/区块链互操作性——了解跨链技术.md"
  - "区块链":
    - "正文": "区块链常识/区块链/区块链.md"
    - "Solana": "区块链常识/区块链/Solana.md"
    - "TON": "区块链常识/区块链/TON.md"
    - "基于EVM": "区块链常识/区块链/基于EVM.md"
    - "L2区块链": "区块链常识/区块链/L2区块链.md"
    - "相关网页中文翻译":
      - "正文开头":
        - "区块链的类型：PoW、PoS 和私有": "区块链常识/中文网页/区块链-中文网页/正文开头/区块链的类型：PoW、PoS 和私有.md"
        - "区块链的类型": "区块链常识/中文网页/区块链-中文网页/正文开头/区块链的类型.md"
      - "Solana":
        - "什么是 Solana，它是如何工作的？": "区块链常识/中文网页/区块链-中文网页/Solana/什么是 Solana，它是如何工作的？.md"
        - "Solana 初学者指南": "区块链常识/中文网页/区块链-中文网页/Solana/Solana 初学者指南.md"
      - "TON":
        - "TON Telegram 集成突出了区块链社区的协同作用": "区块链常识/中文网页/区块链-中文网页/TON/TON Telegram 集成突出了区块链社区的协同作用.md"
        - "区块链分析": "区块链常识/中文网页/区块链-中文网页/TON/区块链分析.md"
      - "基于EVM":
        - "什么是以太坊虚拟机？": "区块链常识/中文网页/区块链-中文网页/基于EVM/什么是以太坊虚拟机？.md"
        - "以太坊":
          - "以太坊简介": "区块链常识/中文网页/区块链-中文网页/基于EVM/以太坊/以太坊简介.md"
        - "币安智能链":
          - "BNB链概述": "区块链常识/中文网页/区块链-中文网页/基于EVM/币安智能链/BNB链概述.md"
      - "L2区块链":
        - "Layer-1 和 Layer-2 区块链扩展解决方案": "区块链常识/中文网页/区块链-中文网页/L2区块链/Layer-1 和 Layer-2 区块链扩展解决方案.md"
        - "Layer- 2 币安学院": "区块链常识/中文网页/区块链-中文网页/L2区块链/Layer- 2 币安学院.md"
  - "more":
    - "正文": "区块链常识/more.md"
- "Oracles":
  - "区块链预言机":
    - "正文": "Oracles/区块链预言机.md"
    - "相关网页中文翻译":
      - "什么是区块链预言机？": "Oracles/中文网页/区块链预言机-中文网页/什么是区块链预言机？.md"
  - "混合智能合约":
    - "正文": "Oracles/混合智能合约.md"
    - "相关网页中文翻译":
      - "混合智能合约解释": "Oracles/中文网页/混合智能合约-中文网页/混合智能合约解释.md"
      - "了解混合智能合约的完整指南": "Oracles/中文网页/混合智能合约-中文网页/了解混合智能合约的完整指南.md"
  - "Chainlink":
    - "正文": "Oracles/Chainlink.md"
    - "相关网页中文翻译":
      - "什么是Chainlink？": "Oracles/中文网页/Chianlink-中文网页/什么是Chainlink？.md"
      - "5 分钟了解 Chainlink": "Oracles/中文网页/Chianlink-中文网页/5 分钟了解 Chainlink.md"
  - "Oracles 网络":
    - "正文": "Oracles/Oracles网络.md"
    - "相关网页中文翻译":
      - "分散的 Oracle 网络": "Oracles/中文网页/Oracles网络-中文网页/分散的 Oracle 网络.md"
      - "去中心化 Oracle 网络发展的新手指南": "Oracles/中文网页/Oracles网络-中文网页/分散的 Oracle 网络.md"
      - "了解Oracle 网络": "Oracles/中文网页/Oracles网络-中文网页/了解Oracle 网络.md"
- "智能合约":
  - "智能合约":
    - "正文": "智能合约/智能合约.md"
    - "相关网页中文翻译":
      - "智能合约简介": "智能合约/中文网页/智能合约-中文网页/智能合约简介.md"
      - "什么是智能合约？": "智能合约/中文网页/智能合约-中文网页/什么是智能合约？.md"
      - "智能合约 - 简单解释": "智能合约/中文网页/智能合约-中文网页/智能合约 - 简单解释.md"
  - "ERC代币":
    - "正文": "智能合约/ERC代币.md"
  - "加密钱包":
    - "正文": "智能合约/加密钱包.md"
    - "相关网页中文翻译":
      - "什么是区块链钱包？": "智能合约/中文网页/加密钱包-中文网页/什么是区块链钱包？.md"
      - "什么是加密钱包？ 初学者指南": "智能合约/中文网页/加密钱包-中文网页/什么是加密钱包？ 初学者指南.md"
  - "加密水龙头（Crypto Faucets）":
    - "正文":  "智能合约/加密水龙头（Crypto Faucets）.md"
    - "相关网页中文翻译":
      - "什么是加密水龙头？": "智能合约/中文网页/集成开发环境（IDEs）-中文网页/什么是加密水龙头？.md"
      - "什么是加密水龙头，以及它们是如何工作的?": "智能合约/中文网页/集成开发环境（IDEs）-中文网页/什么是加密水龙头，以及它们是如何工作的？.md"
  - "去中心化存储":
    - "正文": "智能合约/去中心化存储.md"
    - "相关网页中文翻译":
      - "什么是去中心化存储？": "智能合约/中文网页/去中心化存储-中文网页/什么是去中心化存储？.md"
      - "去中心化存储": "智能合约/中文网页/去中心化存储-中文网页/去中心化存储.md"
  - "测试":
    - "正文": "智能合约/测试.md"
    - "相关网页中文翻译":
      - "如何测试以太坊智能合约": "智能合约/中文网页/测试-中文网页/如何测试以太坊智能合约.md"
      - "编写自动化智能合约测试": "智能合约/中文网页/测试-中文网页/编写自动化智能合约测试.md"
      - "在 Solidity 中对以太坊智能合约进行单元测试的技巧": "智能合约/中文网页/测试-中文网页/在 Solidity 中对以太坊智能合约进行单元测试的技巧.md"
      - "Hardhat 中的智能合约代码覆盖率": "智能合约/中文网页/测试-中文网页/Hardhat 中的智能合约代码覆盖率.md"
  - "部署":
    - "正文": "智能合约/部署.md"
    - "相关网页中文翻译":
      - "部署智能合约并与之交互": "智能合约/中文网页/部署-中文网页/部署智能合约并与之交互.md"
  - "监控":
    - "正文": "智能合约/监控.md"
  - "升级":
    - "正文": "智能合约/升级.md"
    - "相关网页中文翻译":
      - "升级智能合约": "智能合约/中文网页/升级-中文网页/升级智能合约.md"
      - "什么是可升级智能合约？ 完整指南": "智能合约/中文网页/升级-中文网页/什么是可升级智能合约？ 完整指南.md"

#  标记：这以下使用的不再是"正文"

- "编程语言":
  - "编程语言-智能合约": "编程语言/编程语言-智能合约.md"
  - "智能合约": 
    - "Solidity": "编程语言/智能合约/Solidity.md"
    - "Vyper": "编程语言/智能合约/Vyper.md"
    - "Rust": "编程语言/智能合约/Rust.md"
  - "编程语言-智能合约周边开发": "编程语言/编程语言-智能合约周边开发.md"
  - "智能合约 周边开发": 
    - "JavaScript": "编程语言/智能合约 周边开发/JavaScript.md"
    - "Go": "编程语言/智能合约 周边开发/Go.md"
    - "Python": "编程语言/智能合约 周边开发/Python.md"
  - "相关网页中文翻译":
    - "如何在 Rust 中编写和部署智能合约": "编程语言/中文网页/如何在 Rust 中编写和部署智能合约-中文网页.md"
    - "在 Y 分钟内学习 Vyper": "编程语言/中文网页/在 Y 分钟内学习 Vyper-中文网页.md"

- "智能合约框架":
  - "智能合约框架": "智能合约框架/智能合约框架.md"
  - "相关网页中文翻译":
    - "以太坊开发者工具的权威列表 - 框架": "智能合约框架/中文网页/以太坊开发者工具的权威列表 - 框架.md"
    - "2022 年您需要的 10 大智能合约开发工具": "智能合约框架/中文网页/2022 年您需要的 10 大智能合约开发工具.md"

- "安全":
  - "安全": "安全/安全.md"
  - "实践": "安全/实践.md"
  - "工具": "安全/工具.md"
  - "相关网页中文翻译":
    - "以太坊智能合约安全建议": "安全/中文网页/以太坊智能合约安全建议.md"
    - "实践":
      - "智能合约模糊测试入门": "安全/中文网页/实践/智能合约模糊测试入门.md"
      - "Solidity智能合约静态代码分析": "安全/中文网页/实践/Solidity智能合约静态代码分析.md"
      - "Solidity Security：已知攻击向量和常见反模式的综合列表": "安全/中文网页/实践/Solidity Security：已知攻击向量和常见反模式的综合列表.md"
      - "区块链攻击向量：最安全技术的漏洞": "安全/中文网页/实践/区块链攻击向量：最安全技术的漏洞.md"
      - "智能合约随机性或复制逻辑攻击": "安全/中文网页/实践/智能合约随机性或复制逻辑攻击.md"

- "管理平台":
  - "管理平台": "管理平台/管理平台.md"

- "版本控制系统":
  - "版本控制系统": "版本控制系统/版本控制系统.md"

- "代码托管服务":
  - "代码托管服务": "代码托管服务/代码托管服务.md"
  - "GitHub": "代码托管服务/Github.md"
  - "GitLab": "代码托管服务/GitLab.md"
  - "Bitbucket": "代码托管服务/Bitbucket.md"
  - "相关中文网页翻译":
    - "如何在专业开发团队中使用 Git": "代码托管服务/中文网页/如何在专业开发团队中使用 Git.md"

- "Dapp":
  - "dapp": "Dapp/Dapp.md"
  - "前端框架":
    - "前端框架": "Dapp/前端框架/前端框架.md"
    - "React": "Dapp/前端框架/React.md"
    - "Angular": "Dapp/前端框架/Angular.md"
    - "Vue.js": "Dapp/前端框架/vue.js.md"
  - "测试": "Dapp/测试.md"
  - "部署": "Dapp/部署.md"
  - "维护": "Dapp/维护.md"
  - "体系": "Dapp/体系.md"
  - "安全": "Dapp/安全.md"
  - "适用性": 
    - "适用性": "Dapp/适用性/适用性.md"
    - "去中心化金融（DeFi）": "Dapp/适用性/去中心化金融（DeFi）.md"
    - "DAO": "Dapp/适用性/DAO.md"
    - "NFTs": "Dapp/适用性/NFTs.md"
    - "付款": "Dapp/适用性/付款.md"
    - "保险": "Dapp/适用性/保险.md"
  - "节点及服务(NaaS)": "Dapp/节点及服务（NaaS）/节点即服务 (NaaS).md"
  - "客户端库": "Dapp/客户端库/客户端库.md"
  - "客户端节点": "Dapp/客户端节点/客户端节点.md"
  - "相关中文网页翻译":
    - "什么是 Dapp？ 去中心化应用解释": "Dapp/中文网页/什么是 Dapp？ 去中心化应用解释.md"
    - "前端框架":
      - "React 初学者指南": "Dapp/中文网页/前端框架/React 初学者指南.md"
      - "Web3 前端——你需要了解的关于构建 Dapp 前端的一切": "Dapp/中文网页/前端框架/Web3 前端——你需要了解的关于构建 Dapp 前端的一切.md"
    - "测试":
      - "如何测试 dApp（去中心化应用程序）": "Dapp/中文网页/测试/如何测试 dApp（去中心化应用程序）.md"
      - "什么是软件测试？": "Dapp/中文网页/测试/什么是软件测试？.md"
    - "部署":
      - "使用集成 Web3 监控构建以太坊 DApp 的教程": "Dapp/中文网页/部署/使用集成 Web3 监控构建以太坊 DApp 的教程.md"
    - "体系":
      - "Web 3.0 应用程序的架构": "Dapp/中文网页/体系/Web 3.0 应用程序的架构.md"
    - "安全":
      - "dApp 安全：所有你需要知道的": "Dapp/中文网页/安全/dApp 安全：所有你需要知道的.md"
      - "dAPP 安全标准": "Dapp/中文网页/安全/dAPP 安全标准.md"
    - "适用性":
      - "区块链技术的真实用例": "Dapp/中文网页/适用性/区块链技术的真实用例.md"
      - "什么是 dApp？ 去中心化应用指南": "Dapp/中文网页/适用性/什么是 dApp？ 去中心化应用指南.md"
      - "去中心化金融（DeFi）":
        - "去中心化金融（DeFi）定义": "Dapp/中文网页/适用性/去中心化金融（DeFi）/去中心化金融（DeFi）定义.md"
        - "什么是去中心化金融（DeFi）？": "Dapp/中文网页/适用性/去中心化金融（DeFi）/什么是去中心化金融（DeFi）？.md"
      - "DAO":
        - "去中心化自治组织 (DAO)": "Dapp/中文网页/适用性/DAO/去中心化自治组织 (DAO).md"
        - "什么是 DAO，它们是如何工作的？": "Dapp/中文网页/适用性//DAO/什么是 DAO，它们是如何工作的？.md"
      - "NFTs":
        - "NFT，解释": "Dapp/中文网页/适用性/NFTs/NFT，解释.md"
        - "不可替代代币 (NFT)": "Dapp/中文网页/适用性/NFTs/不可替代代币 (NFT).md"
      - "保险":
        - "保险业区块链的 7 大用例": "Dapp/中文网页/适用性/保险/保险业区块链的 7 大用例.md"
    - "节点及服务(NaaS)":
      - "区块链节点提供商及其工作方式": "Dapp/中文网页/节点及服务(NaaS)/区块链节点提供商及其工作方式.md"
- "建设Scale":
  - "建设Scale": "建设Scale/建设Scale.md"
  - "中文网页":
    - "状态通道基础": "建设Scale/中文网页/状态通道基础.md"
    - "状态通道：链下交易简介": "建设Scale/中文网页/状态通道：链下交易简介.md"
    - "Optimistic Rollups 如何工作（完整指南）": "建设Scale/中文网页/Optimistic Rollups 如何工作（完整指南）.md"
    - "什么是 zk-SNATRK ，以及 zk-SNARK 是怎么运作的": "建设Scale/中文网页/什么是 zk-SNATRK ，以及 zk-SNARK 是怎么运作的.md"
    - "zk-SNARK 简介": "建设Scale/中文网页/zk-SNARK 简介.md"














theme:
  name: 'material'
  language: 'zh'  # 配置语言
  palette:  # 颜色
    primary: 'default'
    accent: 'indigo'
  features:
    - navigation.instant # 及时加载
    - navigation.tabs # 增加导航选项卡(横向)
    - navigation.indexes #节索引页(可以删除正文索引了)

    # - toc.follow # 锚点关注(没看出来有什么用)
    # - toc.integrate # 将右选择栏放入左选择栏
    # - navigation.path # 路径显示，但要赞助
    # - navigation.sections # 索引分段